// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfjavjrfzwkvvsshzxsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmamF2anJmendrdnZzc2h6eHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTY3MDIsImV4cCI6MjA2NDM5MjcwMn0.mxmBgNVDvwGP4zHvd5BwY-tFazBlpRTSO9P1US_valc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);